name = "GWNavigation"
uuid = "3f6ca978-1d68-4b56-bb11-f3094904956e"
authors = ["Yohan <Yohan.Karunanayake@anu.edu.au>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
GWNavigationSimExt = "GLMakie"

[compat]
DataStructures = "0.9 - 0.19"
GLMakie = "0.13.6"
POMDPTools = "1.1.0"
POMDPs = "1.0.0"
ParticleFilters = "0.6"
Random = "1.11.0"
StaticArrays = "1.9.15"

[extras]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLMakie"]
